spring.application.name=fitlog
spring.datasource.url=jdbc:mysql://localhost:3306/fit
spring.datasource.username=root
spring.datasource.password=abi#2007
spring.jpa.hibernate.ddl-auto=update
server.port=8081